### ISSUE TITLE
Seriously out-of-date "UV-CDAT Utilities - CHAPTER 3" documentation

### ISSUE THREAD

**Issue by jypeter** [CDAT/cdat.github.io#192]
@doutriaux1 @davis278 A colleague asked some questions about the `eofs` package and I googled `cdat eof` after answering, to see what CDAT was providing. I landed on https://cdat.llnl.gov/documentation/utilities/utilities-3.html that gives examples using `from eof import Eof` and a data file from Paul Dubois (`f=cdms.open('/home/dubois/clt.nc')`, using `cdms` and not `cdms2`, this is **old**!)

You can load `eofs`, though
```
jypeter@obelix3 - ...jypeter - 43 >conda activate cdat-8.1_py2
(cdat-8.1_py2) jypeter@obelix3 - ...jypeter - 44 >python
Python 2.7.15 | packaged by conda-forge | (default, Feb 28 2019, 04:00:11)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import eof
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named eof
>>> import eofs
>>>
```
I also failed to import other packages mentioned on this page, but maybe they are now somewhere deeper (`dir(cdutil)` and `dir(genutil)` did not show anything, and I did not dig deeper)

```
>>> import trends
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named trends
>>> import ort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named ort
>>> import asciidata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named asciidata
>>> import binaryio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named binaryio
```

**Comment by doutriaux1** [comment]
@jypeter we stopped supporting these a few years back, and we had no requests for them until today. You can find the source package under the `contrib` packages directory on the cdat repo:
(see: https://github.com/CDAT/cdat/tree/master/contrib)
Also the conda recipes for most of them can be found there: https://github.com/CDAT/conda-recipes

But again has not been updated in years.

**Comment by doutriaux1** [comment]
@davis278 when porting cdutil doc to a notebook, it might be worth to mention these links and the fact that these package are no longer part of CDAT as they were external contributions to CDAT and therefore should be maintained via conda by their original developers.

**Comment by jypeter** [comment]
If these packages are no longer supported, you might as well remove them from the documentation. Trimming the documentation where it does not have anything to do with the current version is the way to go

Oh, I have just had a look at the `averager` documentation in [chapter 1](https://cdat.llnl.gov/documentation/utilities/utilities-1.html) that we definitely want to keep, and I see lots of references to `cdms` instead of `cdms2` that can probably be easily corrected

**Comment by doutriaux1** [comment]
@jypeter it is on our todo list to update the cdutil documentation. WE're getting closer. But feel free to help us and take the cdutil doc and put it into a notebook, this will save us a great amount of time!

**Comment by jypeter** [comment]
I was about to report that problem again and found out that I had already opened this issue!

I wonder if you can just completely remove Chapter 3, if @doutriaux1 can confirm that no User Contributed Package is available any more

You could move the index at the end of Chapter 3 to the end of Chapter 2, but I'm not sure it's worth it, since the [Table of Contents](https://cdat.llnl.gov/documentation/utilities/utilities.html) is more useful

**Comment by doutriaux1** [comment]
@jypeter you're right we should remove this.
